#!/usr/bin/env python3
"""Extract 'what we already know' from out/ as Core values.

Rules:
- Prefer out/CORE_* artifacts (generated by *_coregen.py).
- If only legacy artifacts exist under out/<LOCK>/, mark them as "legacy" and
  flag if they appear to be ref-driven (contain 'triage', 'ref', 'compare', etc.).

Outputs:
  out/CORE_AUDIT/core_known_values_v0_1.json
  out/CORE_AUDIT/core_known_values_v0_1.md
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]


def _load(p: Path) -> dict:
    return json.loads(p.read_text(encoding="utf-8"))


def _maybe_ref_driven(obj: dict) -> bool:
    # heuristic markers
    txt = json.dumps(obj, sort_keys=True)
    for k in ["triage", "reference", "ref_", "pdg", "codata", "compare", "target"]:
        if k in txt.lower():
            return True
    return False


def main() -> int:
    items = []

    def add(name: str, path: Path, kind: str, note: str = ""):
        if not path.exists():
            return
        obj = _load(path)
        items.append(
            {
                "name": name,
                "path": str(path.relative_to(REPO)).replace("\\", "/"),
                "kind": kind,
                "ref_driven": _maybe_ref_driven(obj) if kind != "core" else False,
                "note": note,
                "keys": list(obj.keys()) if isinstance(obj, dict) else None,
            }
        )

    # Core-preferred
    add("EW: sin^2(thetaW), mW/mZ", REPO / "out" / "CORE_EW_COUPLING_LOCK" / "ew_coupling_core_v0_1.json", "core")
    add("theta_QCD claim", REPO / "out" / "CORE_THETA_QCD_LOCK" / "theta_qcd_lock_v0_2.json", "core")
    add("CKM candidate", REPO / "out" / "CORE_FLAVOR_LOCK" / "flavor_ud_core_v0_9.json", "core")
    add("PMNS candidate", REPO / "out" / "CORE_FLAVOR_LOCK" / "flavor_enu_core_v0_9.json", "core")
    add("lepton mass candidates v0.4", REPO / "out" / "CORE_LEPTON_MASS_LOCK" / "lepton_mass_lock_core_v0_4.json", "core")
    add("lepton mass candidates v0.5", REPO / "out" / "CORE_LEPTON_MASS_LOCK" / "lepton_mass_lock_core_v0_5.json", "core")
    add("lepton engagement candidate", REPO / "out" / "CORE_LEPTON_ENGAGEMENT_LOCK" / "lepton_engagement_lock_core_v0_1.json", "core")
    add("nu mechanism candidate", REPO / "out" / "CORE_NU_MECHANISM_LOCK" / "nu_mechanism_lock_v0_3.json", "core")

    # Legacy (report only)
    add("legacy FLAVOR (ud)", REPO / "out" / "FLAVOR_LOCK" / "flavor_ud_v0_9.json", "legacy", "legacy path; do not treat verify as Core")
    add("legacy FLAVOR (enu)", REPO / "out" / "FLAVOR_LOCK" / "flavor_enu_v0_9.json", "legacy", "legacy path; do not treat verify as Core")

    out_dir = REPO / "out" / "CORE_AUDIT"
    out_dir.mkdir(parents=True, exist_ok=True)

    j = out_dir / "core_known_values_v0_1.json"
    j.write_text(json.dumps({"version": "v0.1", "items": items}, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    lines = ["# Core known values extracted (v0.1)", "", "| Item | Kind | Path | Ref-driven? | Note |", "|---|---|---|---|---|"]
    for it in items:
        lines.append(f"| {it['name']} | {it['kind']} | {it['path']} | {'YES' if it['ref_driven'] else 'NO'} | {it['note']} |")

    (out_dir / "core_known_values_v0_1.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"WROTE: {j}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
